export class JobsModels {
    JobId:number;
    JobCode:string;
    JobName:string;
    JobTitle:string;
    JobDesc:string;
    PositionId:number;
    WorkId:number;
    WorkExp:number;
    WorkSkills:string;
    CompanyId:number;
    LocationCityId:number;
    LocationStateId:number;
    LocationCountryId:number;
    PostalCode:number;
    ContactPerson:string;
    IsActive:boolean;
    CreatedBy:string;
    CreatedDateTime:Date;
    ModifiedBy:string;
    ModifiedDateTime:Date;
}
